apiVersion: v1
kind: Service
metadata:
  name:  staqe-node-{{VALIDATOR_NAME}}
  labels:
    app.kubernetes.io/name: staqe-node-{{VALIDATOR_NAME}}
    app.kubernetes.io/component: validator-node
spec:
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: consensus
    - port: 8648
      targetPort: 8648
      protocol: TCP
      name: rpc
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: staqe-node-{{VALIDATOR_NAME}}
    app.kubernetes.io/component: validator-node
