image: node:20.11.0-alpine3.19

stages:
  - lint
  - docker-build

include:
  # include the component located in the current project from the current SHA
  - component: $CI_SERVER_HOST/mondata/devops/typescript-cicd-components/lint@1.0.0
    inputs:
      image: node:20.11.0-alpine3.19
      lintOptions: --quiet # lint only for errors

docker-build-backend:
  stage: docker-build
  tags:
    - docker-builds # use runner that can perform docker builds

  image: docker:25.0.1@sha256:7986efdd91d8049771bb935f27c53e4f040494d3274c5e377e54ca1337151c29
  services:
    - docker:25.0.1-dind@sha256:7986efdd91d8049771bb935f27c53e4f040494d3274c5e377e54ca1337151c29

  variables:
    IMAGE: docker.io/mondata/staqe-backend

  script:
    - cd backend
    - docker --version
    - docker info
    - docker build -t $IMAGE:latest .
    # only push if we are on a tag
    - |
      if [ "$CI_COMMIT_TAG" ]; then
        docker login -u mondata -p $DOCKER_HUB_PASSWORD
        docker tag $IMAGE:latest $IMAGE:$CI_COMMIT_TAG
        docker push $IMAGE:$CI_COMMIT_TAG
        docker push $IMAGE:latest
      fi

docker-build-frontend:
  stage: docker-build
  tags:
    - docker-builds # use runner that can perform docker builds

  image: docker:25.0.1@sha256:7986efdd91d8049771bb935f27c53e4f040494d3274c5e377e54ca1337151c29
  services:
    - docker:25.0.1-dind@sha256:7986efdd91d8049771bb935f27c53e4f040494d3274c5e377e54ca1337151c29

  variables:
    IMAGE: docker.io/mondata/staqe-app

  script:
    - docker --version
    - docker info
    - docker build -t $IMAGE:latest .
    # only push if we are on a tag
    - |
      if [ "$CI_COMMIT_TAG" ]; then
        docker login -u mondata -p $DOCKER_HUB_PASSWORD
        docker tag $IMAGE:latest $IMAGE:$CI_COMMIT_TAG
        docker push $IMAGE:$CI_COMMIT_TAG
        docker push $IMAGE:latest
      fi
