# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: staqe-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: staqe-create-validators
subjects:
  - kind: ServiceAccount
    name: staqe-backend
