# allow getting status and patching only the one deployment you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: staqe-create-validators
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["statefulsets", "configmaps", "services", "ingresses"]
    # --> label-based access would be nice but is currently not supported by kubernetes:
    #     https://github.com/kubernetes/kubernetes/issues/44703
    # resourceNames: ["<YOUR DEPLOYMENT NAME>"]
    verbs: ["*"]
